name: Terraform Check and Checkov Scan
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform-format:
    name: Check Terraform Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.1  # Replace with your Terraform version

      - name: Validate Terraform formatting
        run: terraform fmt -check -recursive
        # terraform fmt --check will fail the job if any files need formatting.

  checkov-scan:
    name: Run Checkov Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # # use pip to install and run checkov cli ##  
      # - name: Install Checkov
      #   run: pip install checkov
      #
      # - name: Run Checkov
      #   run: checkov -d .

      ## use Builtin Github Action to run checkov 
      # https://github.com/bridgecrewio/checkov-action
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          path: .
          # run only a specific check_id
          # check: CKV_AWS_1
          # skip a specific check_id, or a comma separated list of check id
          skip_check: CKV2_AWS_35
          quiet: true

  terraform-docs:
    name: Generate Terraform Documentation
    runs-on: ubuntu-latest
    permissions:
        contents: 'read'
        id-token: 'write'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}


      - name: Render terraform docs inside the README.md and push changes back to PR branch
        # https://github.com/terraform-docs/gh-actions
        uses: terraform-docs/gh-actions@v1.2.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"

      # - name: Commit files
      #   run: |
      #     git config --local user.email "akhileshmishrabiz@gmail.com"
      #     git config --local user.name "akhileshmishrabiz"
      #     git commit -m "Terraform docs update" -a

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GH_ACTIONS_PAT }}
      #     branch: ${{ github.ref }}


          
